apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-inform
spec:
  selector:
    name: unifi-controller
  ports:
    - name: "tcp8080"
      protocol: TCP
      port: 80
      targetPort: 8080
